PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail

  Fasterer:
    enabled: true
    on_warn: fail

  BundleAudit:
    enabled: true
    on_warn: fail

PrePush:
  Brakeman:
    enabled: true
    on_warn: fail
    
  RSpec:
    enabled: true
    on_warn: fail
