PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail

  Fasterer:
    enabled: true
    on_warn: fail

  BundleAudit:
    enabled: true
    on_warn: fail

  RailsBestPractices:
    enabled: true
    on_warn: fail

  HamlLint:
    enabled: true
    on_warn: fail

  DatabaseConsistency:
    enabled: true
    quiet: false
    command: ['bundle', 'exec', 'database_consistency']

  RubyCtiric:
    enabled: true
    quiet: false
    command: ['bundle', 'exec', 'rubycritic --format console']

PrePush:
  Brakeman:
    enabled: true
    on_warn: fail

  RSpec:
    enabled: true
    on_fail: fail
