PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail

  Fasterer:
    enabled: true
    on_warn: fail

  BundleAudit:
    enabled: true
    on_warn: fail
  
  RailsBestPractices:
    enabled: true
    on_warn: fail
  
  DatabaseConsistency:
    enabled: true
    quiet: false
    command: ['bundle', 'exec', 'database_consistency']

  RailsBestPractices:
    enabled: true
    on_warn: fail

  # DatabaseConsistency:
  #   enabled: true
  #   quiet: false
  #   command: ['bundle', 'exec', 'database_consistency']

PrePush:
  Brakeman:
    enabled: true
    on_warn: fail

  RSpec:
    enabled: true
    on_warn: fail
