require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7.2

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/ArgumentsForwarding:
  Exclude:
    - 'app/services/concerns/callable.rb'

Layout/LineLength:
  Max: 120

RSpec/MessageSpies:
  EnforcedStyle: receive

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'

LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'
