default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_development
  username: et
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: bookstore_test
  username: et
  password: postgres
  host: localhost
  port: 5432
